### ISSUE TITLE
no photos show me

### ISSUE THREAD

**Issue by ForouzanFn** [mnboos/marching-squares#1]
Hello
I have a question. When I run this code nothing doesn't happen. and no photos show me. what should I do?

**Comment by mnboos** [comment]
The code is a bit incomplete. However, to actually use it, you can slightly change the `March()` method from private to public and just return the created vectors (i.e. the result from the `CreateVectors` method).

https://github.com/mnboos/marching-squares/blob/17f74376bd3aa3a7a7654f52d1767a531ccc7ae9/MarchingSquares.cs#L131-L151

**Comment by ForouzanFn** [comment]
Thank you for your answer. Your code detects the outline of an image. Is it write?
And It only detects the outline of black & white images, or it can detect RGBA images?

**Comment by mnboos** [comment]
Yes it detects outlines. For simplicity, it's currently based on the red value of a pixel:

https://github.com/mnboos/marching-squares/blob/17f74376bd3aa3a7a7654f52d1767a531ccc7ae9/MarchingSquares.cs#L110-L113
